name: 'Dependency Security Audit'

on:
  pull_request:
    branches: [main]
    paths:
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Monday
  workflow_dispatch:

jobs:
  audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --production
        continue-on-error: true # Prevents non-critical issues from failing the workflow

      - name: Run npm audit for critical issues
        run: npm audit --audit-level=critical --production
        # This will fail if there are critical issues
